FROM node:24-trixie-slim

# Install deps first for better caching
RUN npm i -g pnpm
COPY ./frontend/package.json ./
COPY ./frontend/pnpm-lock.yaml ./
RUN pnpm install

# Copy rest of the source
COPY . .

# Expose Vite dev server
EXPOSE 5173

CMD ["pnpm", "dev", "--host"]
