services:
  postgres:
    image: postgres
    restart: unless-stopped
    container_name: postgres_natlib
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./pg_data
